### Get all auctions
GET http://{{host}}:{{port}}/auctions
Accept: application/json

> {%
client.test("Request executed successfully", function() {client.assert(response.status === 200, "Response status is not 200");});
%}

### Get auction with id 1
GET http://{{host}}:{{port}}/auctions/1
Accept: application/json

> {%
client.test("Request executed successfully", function() {client.assert(response.status === 200, "Response status is not 200");});
%}

### Create new auction
POST http://{{host}}:{{port}}/auctions
Content-Type: application/json

{
  "item" : "Mona Lisa",
  "category" : "Arts",
  "isClosed" : "true",
  "startingTime" : "December 15, 2021 8:00 PM",
  "duration" : "",
  "details" : "Painting by Kate Muriel Mason",
  "startingPrice" : "12345 GBP"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Update auction with id 1
PUT http://{{host}}:{{port}}/auctions/1
Content-Type: application/json

{
  "item" : "Mona Lisa",
  "category" : "Arts",
  "isClosed" : "false",
  "startingTime" : "December 14, 2021 8:00 PM",
  "duration" : "",
  "details" : "Painting by Leonardo da Vinci",
  "startingPrice" : "99999 GBP"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Delete auction with id 1
DELETE http://{{host}}:{{port}}/auctions/1
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

%}
